apiVersion: v1
kind: Secret
metadata:
  name: ops-manager-admin-secret
  namespace: mongodb
type: Opaque
stringData:
  Username: "admin@mongodb.com"
  Password: "Password1!"
  FirstName: "Admin"
  LastName: "User"
