apiVersion: v1
kind: ConfigMap
metadata:
  name: project-demo
  namespace: mongodb
data:
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080
  orgId: 6a57967607926b6c62307933
  projectName: project-demo