apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mms-scram-user-1
  namespace: mongodb
spec:
  passwordSecretKeyRef:
    name: mms-user-1-password
    key: password
  username: "mms-scram-user-1"
  db: "admin"
  mongodbResourceRef:
    name: "demo-mongodb-cluster-1"
  roles:
    - db: "admin"
      name: "clusterAdmin"
    - db: "admin"
      name: "userAdminAnyDatabase"
    - db: "admin"
      name: "readWrite"